spring:
  application:
    name: immo-user-account
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:user_account_db}
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_USER:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://immo-eureka-server:8761/eureka
  instance:
    hostname: immo-user-account


server:
  port: 8081
  servlet:
    context-path: /api

keyStore:
  path: keystore.jks
  password: password
  alias: auth-server